require('plugins.plugins')
require('plugins.configs.treesitter');
require('plugins.configs.autopairs');
require('plugins.configs.fidget');
require('plugins.configs.telescope');
require('plugins.configs.harpoon');
require('plugins.configs.dap');
require('plugins.configs.colorizer');
require('plugins.configs.blankline');
require('plugins.configs.conform');
require('keymaps')
require('editor')
require('lsp')
require('globals')
